### ISSUE TITLE
PortAudio is not initialized

### ISSUE THREAD

**Issue by hughrawlinson** [peterbourgon/goop#2]
Hi,
I've been trying to give goop a go, but ran into this issue...
I installed portaudio on my mac (`brew install portaudio`), then ran `go get code.google.com/p/portaudio-go/portaudio`. Ran `go build` in the directory, which seemed to work, but then when I run `./goop`, I get the following error:

```
DEBUG Mixer Children() is called
DEBUG Dot: adding edges for 0 children of mixer
DEBUG Mixer Children() is called
DEBUG clock operating at 500.000032ms
panic: open: PortAudio not initialized

goroutine 21 [running]:
runtime.panic(0x40d3f20, 0xc208000260)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*Mixer).Play(0xc2080181e0)
    /Users/hugh/Documents/Development/gocode/goop/mixer.go:149 +0x230
created by main.NewMixer
    /Users/hugh/Documents/Development/gocode/goop/mixer.go:53 +0x1d4

goroutine 16 [syscall]:
syscall.Syscall(0x5, 0xc2080002ca, 0x1000602, 0x1b6, 0x0, 0xc208028b60, 0x403b8f4)
    /usr/local/go/src/pkg/syscall/asm_darwin_amd64.s:20 +0x5
syscall.Open(0x411dc70, 0x5, 0x1000602, 0xc2000001b6, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/syscall/zsyscall_darwin_amd64.go:885 +0x9a
os.OpenFile(0x411dc70, 0x5, 0x602, 0x1b6, 0x10, 0x0, 0x0)
    /usr/local/go/src/pkg/os/file_unix.go:77 +0x73
os.Create(0x411dc70, 0x5, 0xc208002b30, 0x0, 0x0)
    /usr/local/go/src/pkg/os/file.go:248 +0x54
main.writeDotfile(0xc2080222d0)
    /Users/hugh/Documents/Development/gocode/goop/main.go:50 +0x63
main.Field.Add(0xc2080222d0, 0x42a54a8, 0xc2080224e0, 0x0, 0x0)
    /Users/hugh/Documents/Development/gocode/goop/field.go:20 +0x192
main.main()
    /Users/hugh/Documents/Development/gocode/goop/main.go:21 +0x105

goroutine 19 [finalizer wait]:
runtime.park(0x402cce0, 0x41f2158, 0x41cc169)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x41f2158, 0x41cc169)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
main.(*Mixer).loop(0xc2080181e0)
    /Users/hugh/Documents/Development/gocode/goop/mixer.go:63 +0xa0
created by main.NewMixer
    /Users/hugh/Documents/Development/gocode/goop/mixer.go:52 +0x1bc

goroutine 22 [select]:
main.(*Clock).loop(0xc2080224e0)
    /Users/hugh/Documents/Development/gocode/goop/clock.go:45 +0x331
created by main.NewClock
    /Users/hugh/Documents/Development/gocode/goop/clock.go:33 +0xb2

goroutine 17 [syscall]:
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445
```

Something to do with my sound config maybe? It seems like it can't find any children. Also, is this the right way to run it? Should I be using `go run` instead somehow?
Thanks

**Comment by elkelk** [comment]
I'm having the same issue as above. I'd love to try this out. I actually inadvertently used the same process as above and arrived at a similar error. A README would be great for initial setup.

```
DEBUG Mixer Children() is called
DEBUG Dot: adding edges for 0 children of mixer
DEBUG Mixer Children() is called
DEBUG Mixer Children() is called
DEBUG Dot: adding edges for 0 children of mixer
DEBUG Mixer Children() is called
DEBUG Dot: adding edges for 0 children of clock
DEBUG clock operating at 500.000032ms
panic: open: PortAudio not initialized

goroutine 6 [running]:
main.(*Mixer).Play(0xc820014230)
    /Users/daniel/go/src/github.com/peterbourgon/goop/mixer.go:149 +0x281
created by main.NewMixer
    /Users/daniel/go/src/github.com/peterbourgon/goop/mixer.go:53 +0x28d

goroutine 1 [runnable]:
syscall.Syscall(0x4, 0x3, 0xc8200b6060, 0x52, 0x52, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.write(0x3, 0xc8200b6060, 0x52, 0x60, 0xc820053bd0, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1360 +0x5f
syscall.Write(0x3, 0xc8200b6060, 0x52, 0x60, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/syscall_unix.go:176 +0x4d
os.(*File).write(0xc82009e000, 0xc8200b6060, 0x52, 0x60, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/file_unix.go:232 +0xd0
os.(*File).Write(0xc82009e000, 0xc8200b6060, 0x52, 0x60, 0x52, 0x0, 0x0)
    /usr/local/go/src/os/file.go:139 +0x8a
main.writeDotfile(0xc820010360)
    /Users/daniel/go/src/github.com/peterbourgon/goop/main.go:56 +0x2b8
main.Field.Add(0xc820010360, 0x4797000, 0xc820094000, 0x0, 0x0)
    /Users/daniel/go/src/github.com/peterbourgon/goop/field.go:20 +0x193
main.main()
    /Users/daniel/go/src/github.com/peterbourgon/goop/main.go:21 +0x138

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
main.(*Mixer).loop(0xc820014230)
    /Users/daniel/go/src/github.com/peterbourgon/goop/mixer.go:63 +0xa5
created by main.NewMixer
    /Users/daniel/go/src/github.com/peterbourgon/goop/mixer.go:52 +0x26b

goroutine 18 [runnable]:
syscall.Syscall(0x4, 0x1, 0xc8200c0000, 0x26, 0x26, 0x0, 0x0)
    /usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.write(0x1, 0xc8200c0000, 0x26, 0x40, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1360 +0x5f
syscall.Write(0x1, 0xc8200c0000, 0x26, 0x40, 0x0, 0x0, 0x0)
    /usr/local/go/src/syscall/syscall_unix.go:176 +0x4d
os.(*File).write(0xc820032010, 0xc8200c0000, 0x26, 0x40, 0x0, 0x0, 0x0)
    /usr/local/go/src/os/file_unix.go:232 +0xd0
os.(*File).Write(0xc820032010, 0xc8200c0000, 0x26, 0x40, 0x1, 0x0, 0x0)
    /usr/local/go/src/os/file.go:139 +0x8a
fmt.Fprintf(0x475b300, 0xc820032010, 0xc82004fdb8, 0x1c, 0xc82004fe60, 0x1, 0x1, 0xc82002a5d8, 0x0, 0x0)
    /usr/local/go/src/fmt/print.go:189 +0xb2
fmt.Printf(0xc82004fdb8, 0x1c, 0xc82004fe60, 0x1, 0x1, 0x41612a8, 0x0, 0x0)
    /usr/local/go/src/fmt/print.go:197 +0x94
main.D(0x417cf00, 0x15, 0xc82004fe60, 0x1, 0x1)
    /Users/daniel/go/src/github.com/peterbourgon/goop/debug.go:8 +0xa4
main.(*Clock).loop(0xc820094000)
    /Users/daniel/go/src/github.com/peterbourgon/goop/clock.go:42 +0x11c
created by main.NewClock
    /Users/daniel/go/src/github.com/peterbourgon/goop/clock.go:33 +0xde
```
